[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "summa-crawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
app-file=src/app.py
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "openai>=2.52.0",
    "requests>=2.34.2",
    "streamlit>=1.61.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/crawler", "src/processor", "src/summarizer", "src/utils"]
